server:
    port: 8082
spring:
    datasource:
        username: root
        password: zyc1666033672
        url: jdbc:mysql://localhost:3306/dataset_tagger
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat,wall
            stat-view-servlet:
                enabled: true
                login-password: admin
                login-username: admin
            web-stat-filter:
                enabled: true
            filter:
                stat:
                    slow-sql-millis: 1000
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
mybatis:
    mapper-locations: classpath*:/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
